# Generated by Django 5.2.4 on 2025-07-30 14:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAPIData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_source', models.CharField(max_length=50)),
                ('location_name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('raw_data', models.JSONField()),
                ('processed_data', models.JSONField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='PollutionAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('high_aqi', 'High AQI'), ('rapid_increase', 'Rapid Increase'), ('vehicle_malfunction', 'Vehicle Sensor Malfunction'), ('zone_threshold', 'Zone Threshold Exceeded')], max_length=20)),
                ('message', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollutionZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('zone_type', models.CharField(choices=[('safe', 'Safe (Green)'), ('moderate', 'Moderate (Orange)'), ('danger', 'Danger (Red)')], max_length=10)),
                ('coordinates', models.JSONField()),
                ('description', models.TextField(blank=True)),
                ('aqi_threshold_min', models.IntegerField()),
                ('aqi_threshold_max', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pm25', models.FloatField(help_text='PM2.5 concentration (μg/m³)')),
                ('pm10', models.FloatField(help_text='PM10 concentration (μg/m³)')),
                ('co', models.FloatField(help_text='Carbon Monoxide (mg/m³)')),
                ('no2', models.FloatField(help_text='Nitrogen Dioxide (μg/m³)')),
                ('so2', models.FloatField(help_text='Sulfur Dioxide (μg/m³)')),
                ('o3', models.FloatField(help_text='Ozone (μg/m³)')),
                ('aqi', models.IntegerField(help_text='Air Quality Index')),
                ('temperature', models.FloatField(help_text='Temperature (°C)')),
                ('humidity', models.FloatField(help_text='Humidity (%)')),
                ('wind_speed', models.FloatField(help_text='Wind Speed (m/s)')),
                ('wind_direction', models.FloatField(help_text='Wind Direction (degrees)')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_real_time', models.BooleanField(default=True)),
                ('source', models.CharField(default='vehicle', max_length=50)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='monitoring__timesta_6f0ca4_idx'), models.Index(fields=['latitude', 'longitude'], name='monitoring__latitud_43b548_idx'), models.Index(fields=['aqi'], name='monitoring__aqi_0fc1fa_idx')],
            },
        ),
    ]
